#!/bin/bash
#

function copy_files {
	local SRC="../../t2t/yapps-tt/apps/wstty-agent/work/dists/raw/wstty-agent"
	local TMP=$(pwd)
	cd $(dirname $0)/../
	local DIR=$(pwd)
	cd ${TMP}
	cp -vf ${SRC}/index.js ${DIR}/
	cp -vf ${SRC}/package.json ${DIR}/
	cp -vR ${SRC}/app ${DIR}/
	cp -vR ${SRC}/config ${DIR}/
	cp -vf ${SRC}/../../../../CHANGELOG.md ${DIR}/
}

copy_files $@
